[package]
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"
name = "pale-fire"
version = "0.1.0"

[dependencies]
serde = "1.0.117"

[dependencies.json]
features = ["preserve_order"]
package = "serde_json"
version = "1.0.59"
